include: package:lint/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    type_annotate_public_apis: false

analyzer:
  exclude:
    - lib/**/*.*.dart //
