name: gbuagenda

description: A Schedule App for Gautam Buddha University that doesnt suck.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.0.2
  cupertino_icons: ^1.0.0
  dio: ^4.0.0-beta7
  flutter_riverpod: ^0.14.0+3
  get_it: ^6.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  injectable: null
  json_serializable: ^4.0.2
  sentry: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.0.1
  build_runner: null
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.0.0
  injectable_generator: null
  # For Linting
  lint: ^1.0.1
  timeago: ^3.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  assets:
    - assets/icons/heart.png
    - assets/gbu.png
  uses-material-design: true
  fonts:
    - family: Aileron
      fonts:
        - asset: fonts/aileron/Aileron-Heavy.otf
          weight: 900
    - family: Aileron
      fonts:
        - asset: fonts/aileron/Aileron-Regular.otf
    - family: Aileron
      fonts:
        - asset: fonts/aileron/Aileron-SemiBold.otf
          weight: 500
