name: GbuAgenda

description: A Schedule App for Gautam Buddha University that doesnt suck.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  flutter_riverpod: ^0.12.1
  get_it: ^5.0.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  injectable: null
  json_serializable: ^3.5.0
  sentry_flutter: ^4.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_launcher_icons: ^0.8.1
  hive_generator: ^0.8.2
  injectable_generator: null
  # For Linting
  lint: ^1.0.1
  timeago: ^2.0.29
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  assets:
    - assets/icons/heart.png
    - assets/gbu.png
  uses-material-design: true
  fonts:
    - family: Aileron
      fonts:
        - asset: fonts/aileron/Aileron-Heavy.otf
          weight: 900
    - family: Aileron
      fonts:
        - asset: fonts/aileron/Aileron-Regular.otf
    - family: Aileron
      fonts:
        - asset: fonts/aileron/Aileron-SemiBold.otf
          weight: 500
