name: Flutter CI
on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Export Release Timestamp
        run: echo "APP_VERSION=release_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      # Get flutter dependencies.

      - run: flutter pub get
      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Build apk.
      - name: Build APK For Release
        run: |
          flutter build apk --release --split-per-abi
          ls build/app/outputs/apk/release
        env:
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
            ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}

      # Upload generated apk to the artifacts.
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.PANCAKE }}